#!/bin/sh
cd ${0%/*} || exit    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

restore0Dir

# Get application name
application=$(getApplication)

runApplication blockMesh
runApplication setFields
runApplication $application

#------------------------------------------------------------------------------
